### ISSUE TITLE
getting more people involved in this

### ISSUE THREAD

**Issue by anshulkgupta** [coreatcu/annual-report-2015#2]
Let's get some more folks on the slack/website channel onboard with this? We should have it done in the next 2-3 weeks

**Comment by jackiehluo** [comment]
Hahaha, does that count as an issue? But yeah, sure!

**Comment by anshulkgupta** [comment]
As of now, it definitely seems like an 'issue' lol

Sent from my phone.

On Sat, Jul 25, 2015 at 8:41 PM -0700, "Jackie Luo" notifications@github.com wrote:

Hahaha, does that count as an issue? But yeah, sure!

**Comment by jackiehluo** [comment]
Want to send an email? No one is ever on Slack. :cry: Right now, it's just the two of us, so I don't know how effective it would be to ask...
